# Generated by Django 4.2.3 on 2023-08-01 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='phone',
        ),
        migrations.AddField(
            model_name='visitor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
