# Generated by Django 4.2.3 on 2023-08-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_remove_visitor_email_remove_visitor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
