# Generated by Django 4.2.3 on 2023-08-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_place_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='lon',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='lon',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='lon',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='transit',
            old_name='lon',
            new_name='lat',
        ),
    ]
