# Generated by Django 4.2.3 on 2023-08-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_rename_lon_country_lat_rename_lon_place_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='long',
            new_name='lon',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='long',
            new_name='lon',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='long',
            new_name='lon',
        ),
    ]
