# Generated by Django 4.2.3 on 2023-08-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_rename_long_country_lon_rename_long_place_lon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['street']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
