# Generated by Django 4.2.4 on 2023-08-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_alter_address_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-08-16 04:43:35.043897'),
            preserve_default=False,
        ),
    ]
