# Generated by Django 4.2.4 on 2023-08-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0009_trip_alter_visitor_place_tripplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplace',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tripplace',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='countries.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='tripplace',
            unique_together={('trip', 'place', 'date')},
        ),
    ]
