# Generated by Django 4.2.4 on 2023-08-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0010_tripplace_date_alter_tripplace_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplace',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
