# Generated by Django 4.2.4 on 2023-08-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0015_alter_trip_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
