# Generated by Django 4.2.4 on 2023-08-29 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0013_member_alter_visitor_user'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedplace',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.member'),
        ),
    ]
